### ISSUE TITLE
Add requirements.txt file

### ISSUE THREAD

**Issue by mjenczmyk** [gregpinero/ArduinoPlot#3]
I would like to move requirements into `requirements.txt` file to enable installing it into virtualenv with one command. The problem is that `wxPython` cannot be installed that easily with `pip`. Would it be acceptable to leave it as a dependency that has to be installed manually and move other packages requirements into separate file?

**Comment by gregpinero** [comment]
Those are great ideas!  Really, feel free to make any improvements you'd like.

**Comment by gregpinero** [comment]
I added you as a collaborator so you don't have to wait on me to merge pull requests.

**Comment by mjenczmyk** [comment]
Thanks! I once used that library and I found it easy and fun to use, so I thought I could do something to improve it.
