### ISSUE TITLE
wx==3.0.3 required

### ISSUE THREAD

**Issue by jonadem** [gregpinero/ArduinoPlot#5]
Hello,

I installed your application on Ubuntu 16.04 with python 2.7
As said in the README.md, I installed `wxPython Project Phoenix` from a snapshot :
https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-16.04/wxPython-4.0.0a3.dev3059+4a5c5d9-cp27-cp27mu-linux_x86_64.whl

After that, when I start `pip install -r requirements.txt`, I get :

>   Could not find a version that satisfies the requirement wx==3.0.3 (from -r requirements.txt (line 14)) (from versions: )
> No matching distribution found for wx==3.0.3 (from -r requirements.txt (line 14))

If I remove the corresponding line in requirements.txt, it works well.
pip tells me that my version is wxPython (4.0.0a3.dev3059+4a5c5d9)

**Comment by mjenczmyk** [comment]
It looks to me that this pip package is now named `wxPython`. You may uninstall the version installed from snapshot, change `wx==3.0.3` line in `requirements.txt` to `wxPython` and run `pip install -r requirements.txt` (than everything should be fine provided you installed all required system dependencies). For a permanent solution I'll update `requirements.txt` file (with a specific `wxPython` version pinned) and see if everything is works OK.

**Comment by mjenczmyk** [comment]
https://github.com/gregpinero/ArduinoPlot/pull/7

**Comment by mjenczmyk** [comment]
You may use `requirements` branch for now, everything should be fine after its merge to `master`.

**Comment by mjenczmyk** [comment]
I've merged the pull request, I'll close the issue as the problem seems to be solved.
