### ISSUE TITLE
Repository's website URL seems to be broken

### ISSUE THREAD

**Issue by mjenczmyk** [gregpinero/ArduinoPlot#8]
Hey @gregpinero ,

the repository's website URL (http://www.blendedtechnologies.com/realtime-plot-of-arduino-serial-data-using-python/231) seems to be broken - the domain itself seems to lead to nowhere. Could you update it (or remove it if your post cannot be found somewhere else)?

**Comment by gregpinero** [comment]
Hi! I shut down that site a while ago.  You can just remove the reference if you want.  The think the readme covers the basics of what the project is.

**Comment by mjenczmyk** [comment]
I cannot, I don't have sufficient permissions.

**Comment by gregpinero** [comment]
Ok I removed it.  Thanks for catching that.
